services:
  - type: web
    plan: free
    name: Advance-File-Share-Bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    repo: https://github.com/RajbharSaheb/Advance-File-Share-Bot.git      
    branch: master
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH
        sync: false
      - key: ADMINS
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: DATABASE_URL
        sync: false 
      - key: OWNER_ID
        sync: false
      - key: CHANNEL_ID
        sync: false    
    autoDeploy: false 
